# SPDX-License-Identifier: MIT
---

- name: Install git
  package:
    name: git
    state: present

- name: Configure ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: "~{{ ansible_user_id }}/.gitconfig"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
