# SPDX-License-Identifier: MIT
---
- name: Include OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Do not become on mac
- name: Install tools on mac
  package:
    name: "{{ tools_packages_install }}"
    state: present
  when: ansible_os_family == "Darwin"

- name: Install tools
  package:
    name: "{{ tools_packages_install }}"
    state: present
  become: true
  when: ansible_os_family != "Darwin"

