# SPDX-License-Identifier: MIT
---

- name: Configure ~/.vimrc
  template:
    src: vimrc.j2
    dest: "~{{ ansible_user_id }}/.vimrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644

- name: Install plugin vim-ansible-yaml
  git:
    repo: 'https://github.com/chase/vim-ansible-yaml.git'
    dest: "~{{ ansible_user_id }}/.vim/pack/yml/start/vim-ansible-yaml/"
