# SPDX-License-Identifier: MIT
---
- name: Include OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install vim
  package:
    name: "{{ vim_packages_install }}"
    state: present

- name: Configure /etc/vim/vimrc
  template:
    src: vimrc.j2
    dest: "/etc/vim/vimrc"
  when: vimrc_scope == 'system'

- name: Configure ~/.vimrc
  template:
    src: vimrc.j2
    dest: "~{{ vimrc_user }}/.vimrc"
    owner: "{{ vimrc_user }}"
    group: "{{ vimrc_gid }}"
  when: vimrc_scope == 'user'
